# Generated by Django 5.1.7 on 2025-04-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
